### ISSUE TITLE
ReferenceError: next is not defined

### ISSUE THREAD

**Issue by hotfireeagle** [cheeseKun/llss-crawler#1]
```javascript
F:\work\node\dongman_spider\llss-crawler\shenshe.js:45
                  next(err);
                  ^

ReferenceError: next is not defined
    at F:\work\node\dongman_spider\llss-crawler\shenshe.js:45:19
    at Request.callback (F:\work\node\dongman_spider\llss-crawler\node_modules\superagent\lib\node\index.js:688:3)
    at IncomingMessage.<anonymous> (F:\work\node\dongman_spider\llss-crawler\node_modules\superagent\lib\node\index.js:883:18)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1045:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
```
应该是reject(err)?

**Comment by sandfilter** [comment]
报同样的错误，是node版本问题吗
